spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/app__2022_10_11__prod?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password:
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
    hibernate:
      ddl-auto: none
logging:
  level:
    root: info
    com.ll.exam.tossapp.app: info
    org.hibernate.type.descriptor.sql: info
custom:
  site:
    baseUrl: "https://domain"
